### ISSUE TITLE
执行工作调度时失败

### ISSUE THREAD

**Issue by jhj-123** [WeBankFinTech/Schedulis#19]
17-06-2020 09:14:34 CST start INFO - Starting job start at 1592356474832
17-06-2020 09:14:34 CST start INFO - job JVM args: '-Dazkaban.flowid=D' '-Dazkaban.execid=6770' '-Dazkaban.jobid=start'
17-06-2020 09:14:34 CST start INFO - user.to.proxy property was not set, defaulting to submit user hadoop
17-06-2020 09:14:34 CST start INFO - Building command job executor. 
17-06-2020 09:14:34 CST start INFO - Memory granted for job start
17-06-2020 09:14:34 CST start INFO - 1 commands to execute.
17-06-2020 09:14:34 CST start INFO - cwd=/home/DataSphereStudio/AzkabanInstall/azkaban-exec-server-0.1.0-SNAPSHOT/bin/executions/6770
17-06-2020 09:14:34 CST start INFO - effective user is: hadoop
17-06-2020 09:14:34 CST start ERROR - Job run failed!
azkaban.utils.UndefinedPropertyException: Missing required property 'azkaban.native.lib'
	at azkaban.utils.Props.getString(Props.java:450)
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:235)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:813)
	at azkaban.execapp.JobRunner.doRun(JobRunner.java:602)
	at azkaban.execapp.JobRunner.run(JobRunner.java:563)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17-06-2020 09:14:34 CST start ERROR - Missing required property 'azkaban.native.lib' cause: null
17-06-2020 09:14:34 CST start INFO - Finishing job start at 1592356474838 with status FAILED

**Comment by jhj-123** [comment]
1、不是用全家桶安装的，单个安装的

2、以下是报错信息
> 17-06-2020 09:14:34 CST start INFO - Starting job start at 1592356474832
> 17-06-2020 09:14:34 CST start INFO - job JVM args: '-Dazkaban.flowid=D' '-Dazkaban.execid=6770' '-Dazkaban.jobid=start'
> 17-06-2020 09:14:34 CST start INFO - user.to.proxy property was not set, defaulting to submit user hadoop
> 17-06-2020 09:14:34 CST start INFO - Building command job executor.
> 17-06-2020 09:14:34 CST start INFO - Memory granted for job start
> 17-06-2020 09:14:34 CST start INFO - 1 commands to execute.
> 17-06-2020 09:14:34 CST start INFO - cwd=/home/DataSphereStudio/AzkabanInstall/azkaban-exec-server-0.1.0-SNAPSHOT/bin/executions/6770
> 17-06-2020 09:14:34 CST start INFO - effective user is: hadoop
> 17-06-2020 09:14:34 CST start ERROR - Job run failed!
> azkaban.utils.UndefinedPropertyException: Missing required property 'azkaban.native.lib'
> at azkaban.utils.Props.getString(Props.java:450)
> at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:235)
> at azkaban.execapp.JobRunner.runJob(JobRunner.java:813)
> at azkaban.execapp.JobRunner.doRun(JobRunner.java:602)
> at azkaban.execapp.JobRunner.run(JobRunner.java:563)
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> 17-06-2020 09:14:34 CST start ERROR - Missing required property 'azkaban.native.lib' cause: null
> 17-06-2020 09:14:34 CST start INFO - Finishing job start at 1592356474838 with status FAILED

**Comment by SelfImpr001** [comment]
azkaban. native. Lib cannot be removed

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
