### ISSUE TITLE
schedulers集成到dss运行时报空指针异常

### ISSUE THREAD

**Issue by lixz3321** [WeBankFinTech/Schedulis#64]
schedulers集成到dss运行报错：
Caused by: java.lang.NullPointerException
	at azkaban.jobtype.JobTypeManager.loadJobTypeClassLoader(JobTypeManager.java:281) ~[azkaban-common-0.5.0.jar:?]
	at azkaban.jobtype.JobTypeManager.loadJobTypes(JobTypeManager.java:213) ~[azkaban-common-0.5.0.jar:?]
	at azkaban.jobtype.JobTypeManager.loadPluginJobTypes(JobTypeManager.java:157) ~[azkaban-common-0.5.0.jar:?]
	... 28 more
在源码中可以看到是因为jobtype.lib.dir参数获取不到报出的空指针异常

**Comment by mengfanzhen** [comment]
请问这个问题是否已经解决，我碰到了同样的问题

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
