### ISSUE TITLE
Error injecting constructor, java.io.FileNotFoundException: conf/global.properties (No such file or directory) 启动不了

### ISSUE THREAD

**Issue by aileennian** [WeBankFinTech/Schedulis#80]
2022-02-07 15:10:07.606 ERROR [main] azkaban.utils.StdOutErrRedirect 65 write - com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.io.FileNotFoundException: conf/global.properties (No such file or directory)
  at azkaban.execapp.FlowRunnerManager.<init>(FlowRunnerManager.java:175)
  at azkaban.execapp.FlowRunnerManager.class(FlowRunnerManager.java:108)
  while locating azkaban.execapp.FlowRunnerManager
    for the 3rd parameter of azkaban.execapp.AzkabanExecutorServer.<init>(AzkabanExecutorServer.java:126)
  at azkaban.execapp.AzkabanExecutorServer.class(AzkabanExecutorServer.java:97)
  while locating azkaban.execapp.AzkabanExecutorServer

1 error
2022-02-07 15:10:07.606 ERROR [main] azkaban.utils.StdOutErrRedirect 65 write - 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
2022-02-07 15:10:07.606 ERROR [main] azkaban.utils.StdOutErrRedirect 65 write - 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
2022-02-07 15:10:07.606 ERROR [main] azkaban.utils.StdOutErrRedirect 65 write - 	at azkaban.execapp.AzkabanExecutorServer.main(AzkabanExecutorServer.java:178)
2022-02-07 15:10:07.606 ERROR [main] azkaban.utils.StdOutErrRedirect 65 write - Caused by: java.io.FileNotFoundException: conf/global.properties (No such file or directory)
2022-02-07 15:10:07.606 ERROR [main] azkaban.utils.StdOutErrRedirect 65 write - 	at java.io.FileInputStream.open0(Native Method)
2022-02-07 15:10:07.607 ERROR [main] azkaban.utils.StdOutErrRedirect 65 write - 	at java.io.FileInputStream.open(FileInputStream.java:195)
2022-02-07 15:10:07.607 ERROR [main] azkaban.utils.StdOutErrRedirect 65 write - 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
2022-02-07 15:10:07.607 ERROR [main] azkaban.utils.StdOutErrRedirect 65 write - 	at azkaban.utils.Props.<init>(Props.java:84)
2022-02-07 15:10:07.607 ERROR [main] azkaban.utils.StdOutErrRedirect 65 write - 	at azkaban.utils.Props.<init>(Props.java:74)
2022-02-07 15:10:07.607 ERROR [main] azkaban.utils.StdOutErrRedirect 65 write - 	at azkaban.execapp.FlowRunnerManager.<init>(FlowRunnerManager.java:212)
2022-02-07 15:10:07.607 ERROR [main] azkaban.utils.StdOutErrRedirect 65 write - 	at azkaban.execapp.FlowRunnerManager$$FastClassByGuice$$f5329b23.newInstance(<generated>)
2022-02-07 15:10:07.607 ERROR [main] azkaban.utils.StdOutErrRedirect 65 write - 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)

**Comment by aileennian** [comment]
cp  conf bin/
下即可。
这是一个BUG吧。

**Comment by tuigerphkeeper** [comment]
修改internal/internal-start-executor.sh第20行为azkaban_dir=$(cd $(dirname $0)/../..;pwd)可以正常启动了
这里就是读取exec路径，应该是它这个路径读取的有问题，所以找不到conf目录

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
