### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by hehaa** [WeBankFinTech/Schedulis#89]
2022-06-08 09:20:25.124 INFO  [main] azkaban.jobtype.JobTypeManager 77 loadPlugins - Plugin jobtypes failed to load. java.lang.NullPointerException azkaban.jobtype.JobTypeManagerException: java.lang.NullPointerException
	at azkaban.jobtype.JobTypeManager.loadPluginJobTypes(JobTypeManager.java:161) ~[azkaban-common-0.6.2.jar:?]
	at azkaban.jobtype.JobTypeManager.loadPlugins(JobTypeManager.java:75) [azkaban-common-0.6.2.jar:?]
	at azkaban.jobtype.JobTypeManager.<init>(JobTypeManager.java:61) [azkaban-common-0.6.2.jar:?]
	at azkaban.execapp.FlowRunnerManager.<init>(FlowRunnerManager.java:219) [azkaban-exec-server-0.6.2.jar:?]
	at azkaban.execapp.FlowRunnerManager$$FastClassByGuice$$f5329b23.newInstance(<generated>) [azkaban-exec-server-0.6.2.jar:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) [guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111) [guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) [guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) [guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) [guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) [guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [guice-4.1.0.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194) [guice-4.1.0.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) [guice-4.1.0.jar:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) [guice-4.1.0.jar:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) [guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110) [guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) [guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) [guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) [guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) [guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [guice-4.1.0.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194) [guice-4.1.0.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) [guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019) [guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085) [guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015) [guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054) [guice-4.1.0.jar:?]
	at azkaban.execapp.AzkabanExecutorServer.main(AzkabanExecutorServer.java:178) [azkaban-exec-server-0.6.2.jar:?]
Caused by: java.lang.NullPointerException
	at azkaban.jobtype.JobTypeManager.loadJobTypeClassLoader(JobTypeManager.java:281) ~[azkaban-common-0.6.2.jar:?]
	at azkaban.jobtype.JobTypeManager.loadJobTypes(JobTypeManager.java:213) ~[azkaban-common-0.6.2.jar:?]
	at azkaban.jobtype.JobTypeManager.loadPluginJobTypes(JobTypeManager.java:157) ~[azkaban-common-0.6.2.jar:?]
	... 28 more

**Comment by tuigerphkeeper** [comment]
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/42008109/173239133-213f41b3-b013-4bdd-862f-48983a23f7fa.png">
这里要按上面配置， DataChecker 和 EventChecker 的配置是额外的

**Comment by tuigerphkeeper** [comment]
plugins/jobtypes/common.properties要按文档配置，只是说DataChecker 和 EventChecker插件配置是额外的

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
