### ISSUE TITLE
schedulis 无法登陆WTSS Web Client

### ISSUE THREAD

**Issue by jkl0898** [WeBankFinTech/Schedulis#9]
版本：
schedulis_0.5.0_exec
schedulis_0.5.0_web

现象：
页面点击输入默认用户及密码无反应。
wtss-webserver.log 有如下异常信息：
java.lang.NoClassDefFoundError: org/forgerock/opendj/ldap/LdapException
        at com.webank.wedatasphere.schedulis.common.user.SystemUserManager.getUser(SystemUserManager.java:88)
        at azkaban.webapp.servlet.LoginAbstractAzkabanServlet.createSession(LoginAbstractAzkabanServlet.java:541)
        at azkaban.webapp.servlet.LoginAbstractAzkabanServlet.createSession(LoginAbstractAzkabanServlet.java:520)
        at azkaban.webapp.servlet.LoginAbstractAzkabanServlet.handleAjaxLoginAction(LoginAbstractAzkabanServlet.java:597)
        at azkaban.webapp.servlet.LoginAbstractAzkabanServlet.doPost(LoginAbstractAzkabanServlet.java:448)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
        at com.webank.wedatasphere.schedulis.web.webapp.LocaleFilter.doFilter(LocaleFilter.java:97)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)

**Comment by jkl0898** [comment]
经定位，问题属于打包缺失。web 的zip 包缺少azkaban-common/extlib 的opendj-core-3.0.0.jar 和opendj-grizzly-3.0.0.jar。

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
