### ISSUE TITLE
项目已被删除，不能上传

### ISSUE THREAD

**Issue by hehaa** [WeBankFinTech/Schedulis#93]
2022-06-20 16:57:37.280 ERROR [Convert-Orchestration-Thread-5] com.webank.wedatasphere.dss.orchestrator.publish.job.OrchestratorConversionJob 99 run - Convert for project DSSProject{id=313, name='ESGDataEngine', description='ESG 数据引擎', createBy='esg', username='esg', createTime=Sat Jun 18 23:28:49 CST 2022, updateTime=Sat Jun 18 23:28:49 CST 2022, product='', applicationArea=0, business='', workspaceId=null, workspaceName='null', viewUsers=null, editUsers=null, executeUsers=null} failed. com.webank.wedatasphere.dss.common.exception.DSSErrorException: errCode: 50000 ,desc: errCode: 90012 ,desc: ErrorException: errCode: 90014 ,desc: errCode: 90013 ,desc: release project failed, {
  "error" : "项目已被删除，不能上传."
} ,ip: esg001 ,port: 9005 ,serviceKind: dss-workflow-server-dev ,ip: esg001 ,port: 9005 ,serviceKind: dss-workflow-server-dev ,ip: esg001 ,port: 9005 ,serviceKind: dss-workflow-server-dev ,ip: esg001 ,port: 9003 ,serviceKind: dss-framework-orchestrator-server-dev
	at com.webank.wedatasphere.dss.orchestrator.publish.job.OrchestratorConversionJob.run(OrchestratorConversionJob.java:93) [dss-framework-orchestrator-publish-1.0.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by James23Wang** [comment]
> 2022-06-20 16:57:37.280 ERROR [Convert-Orchestration-Thread-5] com.webank.wedatasphere.dss.orchestrator.publish.job.OrchestratorConversionJob 99 run - Convert for project DSSProject{id=313, name='ESGDataEngine', description='ESG 数据引擎', createBy='esg', username='esg', createTime=Sat Jun 18 23:28:49 CST 2022, updateTime=Sat Jun 18 23:28:49 CST 2022, product='', applicationArea=0, business='', workspaceId=null, workspaceName='null', viewUsers=null, editUsers=null, executeUsers=null} failed. com.webank.wedatasphere.dss.common.exception.DSSErrorException: errCode: 50000 ,desc: errCode: 90012 ,desc: ErrorException: errCode: 90014 ,desc: errCode: 90013 ,desc: release project failed, { "error" : "项目已被删除，不能上传." } ,ip: esg001 ,port: 9005 ,serviceKind: dss-workflow-server-dev ,ip: esg001 ,port: 9005 ,serviceKind: dss-workflow-server-dev ,ip: esg001 ,port: 9005 ,serviceKind: dss-workflow-server-dev ,ip: esg001 ,port: 9003 ,serviceKind: dss-framework-orchestrator-server-dev at com.webank.wedatasphere.dss.orchestrator.publish.job.OrchestratorConversionJob.run(OrchestratorConversionJob.java:93) [dss-framework-orchestrator-publish-1.0.1.jar:?] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

请在 Schedulis 确认该项目是否还存在

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
添加备注，DSS大数据
持续为DataSphereStudio开源贡献力量
